config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: "zoos#index"
  resources :zoos, only: [:index] do
    resources :animals, only: [:index]
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :zoo
  has_one :image, as: :uploadable, dependent: :destroy, class_name: 'Upload'

  validates_presence_of :name, :description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_attached_file :image,
                    styles: { thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  delegate :url, to: :image

  belongs_to :uploadable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/zoo.rb
class Zoo < ApplicationRecord
  has_many :animals, dependent: :destroy
  has_one :image, as: :uploadable, dependent: :destroy, class_name: 'Upload'

  validates_presence_of :name, :address, :city, :state, :zip
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  before_action :set_zoo

  def index
    @animals = @zoo.animals.includes(:image)
  end

  private

  def set_zoo
    @zoo = Zoo.find(params[:zoo_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(user)
    rails_admin_url
  end
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @zoos = Zoo.all.includes(:image)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zoos_helper.rb
module ZoosHelper
  def google_map(address, city, state, zip)
    formatted_address = address
    formatted_address += ", "+city
    formatted_address += ", "+state
    formatted_address += ", "+zip
    "https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE_MAPS_API_KEY']}&q=#{formatted_address}"
  end
end

app/views/animals/index.html.erb
<%= link_to 'Back', zoos_path(), class: 'btn btn-primary m-3'%>
<div class="m-3">
  <table id="animals-table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th> Image</th>
        <th> Name</th>
        <th> Description</th>
      </tr>
    </thead>
    <tbody>
      <% @animals.each do |animal| %>
        <tr>
          <td>
            <%= image_tag(animal.image.url(:thumb)) if animal.image %>
          </td>
          <td><%=animal.name%></td>
          <td><%=animal.description%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<p class="text-center">
  <iframe width="700" height="400" frameborder="0" src="<%= google_map(@zoo.address, @zoo.city, @zoo.state, @zoo.zip) %>"
   allowfullscreen>
  </iframe>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZooApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/zoos/index.html.erb
<%= link_to 'Login as Admin', new_user_session_path(), class: 'align-right m-3'%>
<div class="m-3">
  <table id="zoos-table" class="table table-striped table-bordered">
    <thead>
      <tr>
        <th> Image</th>
        <th> Name</th>
        <th> Address</th>
        <th> City</th>
        <th> State</th>
        <th> Zip</th>
        <th> Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @zoos.each do |zoo| %>
        <tr>
          <td>
            <%= image_tag(zoo.image.url(:thumb)) if zoo.image %>
          </td>
          <td><%=zoo.name%></td>
          <td><%=zoo.address%></td>
          <td><%=zoo.city%></td>
          <td><%=zoo.state%></td>
          <td><%=zoo.zip%></td>
          <td><%= link_to("List Animals", zoo_animals_path(zoo.id))%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>